name: portfolio_api
recipe: drupal10
config:
  webroot: web
  database: mariadb
  php: '8.1'
proxy:
  appserver:
    - portfolio_api.lndo.site
tooling:
  drush:
    service: appserver
    cmd: /app/vendor/drush/drush/drush --root=/app/web
